stages:
  - test
  - build
  - release

.test: &test
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run py.test

test-python3.6:
  image: python:3.6
  <<: *test

test-python3.7:
  image: python:3.7
  <<: *test

test-python3.8:
  image: python:3.8
  <<: *test

build:
  image: python:3.7
  stage: build
  only:
    - tags
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry build
  artifacts:
    paths:
      - dist/
    expire_in: 30 days

release:
  image: python:3.7
  stage: release
  only:
    - tags
  dependencies:
    - build
  before_script:
    - pip install poetry
  script:
    - echo $PYPI_USERNAME
    - poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
